// <auto-generated />
namespace bar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bar_BD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bar_BD));
        
        string IMigrationMetadata.Id
        {
            get { return "201603201013324_bar_BD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
